spring.application.name=Screening
server.port=8081

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
classifier.service.url=${CLASSIFIER_CLIENT_URL}

management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.enabled=true