spring.application.name=gateway-service
server.port=8080
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
questionnaire.service.url=${QUESTIONNAIRE_SERVICE_URL}
screening.service.url=${SCREENING_SERVICE_URL}

management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.enabled=true
