spring.application.name=Emergency_service
server.port = 8084

twilio.account.sid=${TWILIO_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.phone.number=${TWILIO_NUMBER}


# ------------UNCOMMENT FOR LOCAL RUN-------------------
#spring.datasource.url=jdbc:postgresql://localhost:5432/crisis_db
#spring.datasource.username=postgres
#spring.datasource.password=postgres

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

