DOMAIN_PROTOTYPES = {

"ANXIETY":[
"I feel anxious most of the time",
"I constantly worry about many things",
"My mind keeps racing with thoughts",
"I feel nervous and on edge",
"I cannot stop overthinking problems",
"I feel tense and restless",
"I keep anticipating something bad will happen",
"I struggle to relax because my thoughts keep going",
"I feel uneasy even when nothing is wrong",
"My thoughts keep circling around worries",
"I feel panic or sudden fear sometimes",
"I worry about the future constantly",
"I feel like my mind never calms down",
"I feel jittery and uneasy inside",
"I keep worrying about things I cannot control"
],

"DEPRESSION":[
"I feel empty and emotionally numb",
"I feel very down most days",
"Nothing seems enjoyable anymore",
"I have lost interest in things I used to enjoy",
"I feel hopeless about the future",
"I feel like life has no meaning",
"I have very little motivation to do anything",
"I feel sad and low all the time",
"I feel like nothing will ever improve",
"I struggle to find joy in daily life",
"I feel worthless or like a failure",
"I feel emotionally drained and hopeless",
"I feel detached from everything around me",
"I feel like I am stuck in sadness",
"I feel like life has lost its purpose"
],

"ADHD":[
"I struggle to focus on tasks",
"I get distracted very easily",
"I find it hard to concentrate for long",
"I forget things I was supposed to do",
"I often start tasks but never finish them",
"I struggle to stay organized",
"I lose things frequently",
"I feel mentally scattered during work",
"I cannot keep my attention on one thing",
"I jump between tasks without completing them",
"I have difficulty managing my time",
"I find it hard to plan or organize tasks",
"I feel restless when trying to focus",
"I struggle to sit still when working",
"I often forget important details"
],

"SLEEP":[
"I have trouble falling asleep at night",
"I wake up many times during the night",
"My sleep schedule is completely messed up",
"I feel very sleepy during the day",
"I struggle with insomnia frequently",
"I cannot stay asleep through the night",
"I wake up too early and cannot sleep again",
"I feel exhausted because my sleep is poor",
"My sleep feels restless and broken",
"I lie awake in bed for a long time",
"I feel tired even after sleeping",
"I often wake up feeling unrefreshed",
"I struggle to maintain a regular sleep schedule",
"I wake up feeling like I barely slept",
"My sleep problems affect my daily energy"
],

"STRESS":[
"I feel overwhelmed with responsibilities",
"I feel a lot of pressure from work or studies",
"I feel mentally exhausted from everything",
"I feel like I cannot cope with all my tasks",
"I feel constantly stressed about life",
"I feel burned out from work",
"I feel like too many things are expected from me",
"I feel under constant pressure",
"I feel emotionally drained from stress",
"I feel overwhelmed by my workload",
"I feel like I cannot handle everything going on",
"I feel mentally overloaded with responsibilities",
"I feel stressed about deadlines and expectations",
"I feel like I am constantly under pressure",
"I feel like everything is piling up on me"
],

"SOCIAL_ANXIETY":[
"I feel very anxious around other people",
"I worry that people are judging me",
"I avoid social gatherings because they make me nervous",
"I feel uncomfortable talking to strangers",
"I get anxious speaking in front of others",
"I feel embarrassed easily in social situations",
"I avoid conversations because I feel awkward",
"I worry about saying something embarrassing",
"I feel nervous meeting new people",
"I struggle with social interactions",
"I avoid situations where I might be judged",
"I feel anxious when I have to speak publicly",
"I feel uncomfortable being the center of attention",
"I worry people are criticizing me",
"I feel nervous interacting with groups of people"
],

"TRAUMA":[
"I keep having flashbacks about a past event",
"I relive traumatic memories unexpectedly",
"I have nightmares about something bad that happened",
"I avoid places that remind me of a past event",
"I feel constantly on guard after a traumatic experience",
"I get triggered by reminders of something traumatic",
"I struggle with memories of a painful event",
"I feel tense when something reminds me of the past",
"I feel like I am reliving a traumatic moment",
"I certain memories keep coming back vividly",
"I try to avoid thinking about a traumatic experience",
"I I feel emotionally shaken by memories of the past",
"I feel hyper alert after something traumatic",
"I feel anxious when something reminds me of a past trauma",
"I my mind keeps returning to a disturbing memory"
],

"DISTRESS_GENERAL":[
"I feel mentally overwhelmed",
"I feel emotionally unstable lately",
"I feel like my mental health is struggling",
"I feel psychologically exhausted",
"I feel emotionally drained",
"I feel mentally unwell",
"I feel overwhelmed by my emotions",
"I feel like I cannot handle my feelings",
"I feel emotionally out of balance",
"I feel mentally tired and distressed",
"I feel emotionally overwhelmed by life",
"I feel mentally exhausted and confused",
"I feel like my emotions are out of control",
"I feel like I am struggling mentally",
"I feel emotionally and mentally worn out"
],

"SOCIAL_SUPPORT":[
    "I feel like I have no one to turn to for help",
    "I feel completely alone with my problems",
    "I don't have anyone I can talk to about my feelings",
    "I feel isolated from my friends and family",
    "I feel like nobody truly understands me",
    "I lack a support system to rely on",
    "I have no one to share my joys and sorrows with",
    "I feel disconnected from the people around me",
    "I feel like nobody cares about what I am going through",
    "I don't have any close friends to confide in",
    "I feel unsupported by my family and friends",
    "I feel like I have to handle everything on my own",
    "Who can I turn to when I need emotional support?",
    "Why does it feel like I have no one to talk to?",
    "I feel lonely even when I am surrounded by people"
]

}