DOMAIN_PROTOTYPES = {

"ANXIETY":[
    "I constantly worry about many things throughout the day.",
    "I feel terrified that something awful is going to happen today.",
    "I get sudden spikes of panic and start sweating.",
    "My stomach is tied in knots from worrying about the future.",
    "I feel constantly on edge and can't seem to relax physically.",
    "I keep biting my nails and fidgeting because I'm so nervous.",
    "I feel like I'm having a panic attack and can't catch my breath.",
    "I feel jittery and uneasy inside like something is wrong.",
    "I have these sudden feelings of intense fear for no reason.",
    "My thoughts are racing with worst-case scenarios.",
    "I feel breathless and dizzy from sheer worry.",
    "I am constantly anticipating a disaster.",
    "My chest feels tight from anxiety and worry.",
    "I feel nervous and on edge all the time.",
    "I keep worrying about things I cannot control."
],

"DEPRESSION":[
    "Everything feels pointless and I can't find joy in my hobbies.",
    "I feel completely numb and empty inside.",
    "I cry randomly and I don't even know why.",
    "I have zero motivation to do anything at all.",
    "I feel like a burden to everyone around me.",
    "I feel worthless and like my life has no meaning.",
    "I have completely lost interest in things I used to love.",
    "I feel like nothing will ever get better.",
    "I am stuck in deep sadness and despair.",
    "I feel like a failure in every aspect of my life.",
    "I just want to disappear because everything is so bleak.",
    "I feel too exhausted and sad to take care of myself.",
    "A heavy weight of sadness sits on me all day long.",
    "Life feels meaningless and I see no reason to keep going.",
    "I feel deep sorrow that won't go away no matter what I do."
],

"ADHD":[
    "I can't sit still and my mind is jumping from one task to another.",
    "I lose my keys every single day and keep forgetting my meetings.",
    "I start five different projects but never finish any of them.",
    "People tell me I interrupt them constantly without realizing it.",
    "I find it impossible to pay attention when people are talking to me.",
    "My desk is a complete disaster and I can't stay organized.",
    "I get incredibly hyper-focused on weird hobbies and ignore my real work.",
    "I'm always zoning out during important conversations.",
    "I keep forgetting important details and making careless mistakes.",
    "I struggle to manage my time and am always late.",
    "I feel constantly restless, like I'm driven by a motor.",
    "I jump between topics when I'm speaking.",
    "I find it hard to concentrate on reading or studying for long periods.",
    "I am easily distracted by noises and movement around me.",
    "I often misplace things I just had in my hand."
],

"SLEEP":[
    "I wake up at 3 AM every night and stare at the ceiling.",
    "No matter how long I lie down, I just can't fall asleep.",
    "I feel exhausted all day but wired as soon as my head hits the pillow.",
    "I rely on sleeping pills almost every night now.",
    "Even after 9 hours of sleep, I wake up feeling like I got hit by a truck.",
    "I toss and turn for hours before I can finally drift off to sleep.",
    "My sleep schedule is completely upside down.",
    "I suffer from terrible insomnia night after night.",
    "I cannot stay asleep through the night.",
    "I lie awake for a long time trying to sleep.",
    "My sleep feels restless and broken.",
    "I wake up too early and cannot sleep again.",
    "I struggle to maintain a regular sleep schedule.",
    "I wake up feeling like I barely slept.",
    "My sleep problems affect my daily energy."
],

"STRESS":[
    "Work is piling up and I feel like I'm drowning in deadlines.",
    "There is too much pressure on me right now to perform at work.",
    "I have so many work responsibilities I don't even know where to start.",
    "My boss keeps giving me more tasks and I'm at my breaking point.",
    "I feel completely overwhelmed by everything I have to do this week.",
    "The expectations at my job are just way too high.",
    "I'm burnt out from my workload and feel like I'm running on empty.",
    "Trying to balance my job, studies, and life is driving me crazy.",
    "I feel overloaded with work responsibilities.",
    "I am mentally exhausted from my workload at the office.",
    "I feel stressed about work deadlines and expectations.",
    "I feel under constant pressure at my job.",
    "My work tasks are piling up on me.",
    "I feel like I cannot handle my work responsibilities anymore.",
    "The workload at my job is crushing me."
],

"SOCIAL_ANXIETY":[
    "I cancelled my plans because the thought of a party makes me nauseous.",
    "I feel like everyone is staring and judging me when I walk into a room.",
    "I start sweating and shaking when I have to speak up in meetings.",
    "I overthink every single interaction I have with people.",
    "I'd rather stay home alone than face a crowd of strangers.",
    "I rehearse what I'm going to say to the cashier multiple times.",
    "Eye contact feels incredibly intense and uncomfortable for me.",
    "I feel incredibly awkward and out of place in social gatherings.",
    "I worry about saying something embarrassing in public.",
    "I avoid situations where I might be judged by others.",
    "I feel anxious when I have to speak publicly.",
    "I feel uncomfortable talking to strangers.",
    "I feel nervous interacting with groups of people.",
    "I avoid conversations because I feel awkward.",
    "I get anxious speaking in front of others."
],

"TRAUMA":[
    "Loud noises keep bringing me back to that horrible day.",
    "I try not to think about the accident, but the memories keep flashing back.",
    "Ever since the traumatic event, I feel hyper-alert and always watching for danger.",
    "I avoid driving entirely because it reminds me of what happened.",
    "Nightmares about the traumatic event keep waking me up in a cold sweat.",
    "A specific smell brought back vivid memories of the trauma.",
    "I feel numb and disconnected from reality when I remember my past trauma.",
    "I feel like I'm reliving the worst moment of my life over and over.",
    "I relive traumatic memories unexpectedly.",
    "I avoid places that remind me of a past traumatic event.",
    "Certain sensory cues like sounds or smells trigger memories of my trauma.",
    "I feel constantly on guard ever since the traumatic experience.",
    "I feel tense when something reminds me of the traumatic past.",
    "My mind keeps returning to a disturbing traumatic memory.",
    "I keep having flashbacks to a specific traumatic event from my past."
],

"DISTRESS_GENERAL":[
    "I don't feel like myself lately.",
    "I'm struggling a lot mentally these days.",
    "I feel like my mental health has taken a huge dive.",
    "I feel mentally unwell and I can't pinpoint why.",
    "I feel emotionally out of balance.",
    "I feel mentally tired and distressed.",
    "I feel like I am struggling mentally.",
    "I feel emotionally and mentally worn out.",
    "I feel psychologically exhausted.",
    "I feel emotionally unstable lately.",
    "My emotional state has been really poor recently.",
    "I feel like I'm falling apart emotionally.",
    "My mental health feels fragile right now.",
    "My mind feels like a complete mess right now.",
    "I'm just emotionally exhausted and feel terrible."
],

"SOCIAL_SUPPORT":[
    "I literally have nobody to talk to about my problems.",
    "My family doesn't understand me and I feel completely isolated.",
    "I feel like my friends don't actually care about what I'm going through.",
    "I'm surrounded by people but still feel entirely alone.",
    "When I reach out for help, everyone just ignores me.",
    "I have no shoulder to cry on.",
    "It hurts that nobody checks in on me to see how I'm doing.",
    "I feel like an outsider even in my own friend group.",
    "I feel like I have no one to turn to for help.",
    "I feel completely alone with my problems.",
    "I lack a support system to rely on.",
    "I have no one to share my joys and sorrows with.",
    "I feel unsupported by my family and friends.",
    "Who can I turn to when I need emotional support?",
    "I don't have any close friends to confide in."
],

"VAGUE":[
    "I don't know, it's just weird.",
    "Nothing much to say.",
    "I guess I'm fine.",
    "Whatever.",
    "Not sure how to put it into words.",
    "It's kind of hard to explain.",
    "Things are just okay.",
    "I don't really have anything specific on my mind.",
    "I am not sure.",
    "Nothing much.",
    "I can't explain it.",
    "I have no idea.",
    "It's hard to say.",
    "I don't know what to say.",
    "I'm not certain."
]

}